version: "3.8"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: punto-venta
    container_name: punto-venta
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - local-network

  db:
    image: mysql:8
    container_name: punto-venta-db
    restart: unless-stopped
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - local-network

  nginx:
    image: nginx:1.25-alpine
    container_name: punto-venta-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - local-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: punto-venta-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
        - db
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
